name: Linting
on:
  push:
    branches:
      - vale-2.0

jobs:
  rubocop:
    name: Rubocop
    runs-on: ubuntu-latest
    timeout-minutes: 30
    steps:
      - uses: actions/checkout@v2

      # Configure Ruby to build Jekyll site
      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: 2.7.2
      - name: Ruby gem cache
        uses: actions/cache@v2
        with:
          path: ${{ github.workspace }}/vendor/bundle
          key: ${{ runner.os }}-gems-${{ hashFiles('**/Gemfile.lock') }}
          restore-keys: |
            ${{ runner.os }}-gems-
      - name: Bundle Setup
        run: bundle config path ${{ github.workspace }}/vendor/bundle
      - name: Bundle Install
        run: bundle install --jobs 4 --retry 3

      - name: Rubocop
        run: |
          bundle exec rubocop app
  vale:
    name: Vale
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: errata-ai/vale-action@v2.0.1
        with:
          # path where vale checks checking only modified files.
          files: __onlyModified
          onlyAnnotateModifiedLines: true
        env:
          GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}