name: text-linting
on:
  push:
    branches:
      - vale-branch

jobs:
  vale:
    name: runner / vale
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Get Changed Files
      id: get_changed_files
      uses: lots0logs/gh-action-get-changed-files@2.1.4
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
    - name: List Commit Files
      id: list_commit_files
      run: |
        echo "Vale will check the following files:"
        cat ${HOME}/files.json
    - name: Run Vale
      uses: errata-ai/vale-action@v2.0.1
      with:
        files: __onlyModified
      env:
        GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}